DROP TABLE IF EXISTS seller;
DROP TABLE IF EXISTS product;

CREATE TABLE seller(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE product(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    product_name TEXT NOT NULL,
    product_description TEXT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES seller(id)
);